"""Turn reports/bench/*.json into reports/comparison.md.

Every number in the generated table comes from a file written by core/bench.py
during an actual run. Nothing here is typed by hand, which is the whole point:
the READMEs currently carry figures whose conditions nobody recorded, so two
of them cannot be compared even in principle.

The table is grouped by input size rather than flattened across all models.
That is deliberate. Three models do not run at 518 -- depth_pro is fixed at
1536, metric3d_v2 at 616x1064, moge_2 at 388x518 -- and attention cost is
quadratic in token count, so a single ranked list would just be a list of
which model got the smallest input. See docs/model_contracts.md 2.

usage:
    python compare.py                 # reports/bench -> reports/comparison.md
    python compare.py --check         # exit 1 if the file is out of date
"""

import argparse
import os
import sys
from collections import defaultdict

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from core.bench import load_all  # noqa: E402

ROOT = os.path.dirname(os.path.abspath(__file__))
BENCH_DIR = os.path.join(ROOT, "reports", "bench")
OUT = os.path.join(ROOT, "reports", "comparison.md")

# What each model's depth numbers actually mean. Mirrors the classification in
# docs/model_contracts.md 1; keep the two in step. This lives here rather than
# in a data file until spec.json lands in Phase 4.
KIND = {
    # depth_anything_v2 ships both a relative and a metric checkpoint and the
    # scripts default to metric_model=True with the hypersim (indoor) weights,
    # so that is what a default build measures. Flip metric_model in
    # onnx_export.py and onnx2trt.py together for the relative one.
    "depth_anything_v2": "metric (hypersim) by default",
    "depth_anything_ac": "relative",
    "depth_anything_v3": "relative + sky mask",
    "distill_any_depth": "relative",
    "depth_pro": "metric",
    "metric3d_v2": "canonical (not metres - D12)",
    "moge_2": "point map + metric_scale",
    "metric_anything": "point map + metric_scale",
    "unidepth_v2": "point map + intrinsics",
    "unik3d": "point map + intrinsics",
    "vggt": "geometry (scale unknown)",
    "streamvggt": "geometry (scale unknown)",
}

# Model key -> folder, for the cases where the two disagree today. The key is
# what goes in a result file and a report; the folder is where the scripts
# live. Phase 4 renames the folders to match, at which point this collapses to
# a plain lowercase() and can go away. Until then the mismatch is written down
# rather than papered over -- an undeclared one silently drops a model from
# the coverage check in tests/test_compare.py.
FOLDER = {
    "unidepth_v2": "Uni_Depth_V2",   # upstream calls it UniDepthV2
}

# Caveats that must travel with the number, or a reader will draw the wrong
# conclusion from a table that looks authoritative.
CAVEAT = {
    "unidepth_v2": "metric scale ~3.1x upstream at 518x518 (D11)",
    "unik3d": "metric scale 3.15x upstream at 518x518 (D11)",
    "metric3d_v2": "output is canonical depth, not metres (D12)",
    "metric_anything": "stretched to square; intrinsics use aspect 1.0 (D13)",
}


def _fmt(x, nd=2):
    return "-" if x is None else f"{x:.{nd}f}"


def _size(r):
    h, w = r.get("input_h") or 0, r.get("input_w") or 0
    return f"{h}x{w}" if h and w else "?"


def _rows(runs):
    for r in sorted(runs, key=lambda r: (r["model"], r.get("precision", ""))):
        s = r.get("stats") or {}
        yield [
            f"`{r['model']}`",
            r.get("variant", "single"),
            r.get("precision", "?"),
            _fmt(s.get("mean_ms")),
            _fmt(s.get("p50_ms")),
            _fmt(s.get("p90_ms")),
            _fmt(s.get("fps")),
            KIND.get(r["model"], "?"),
        ]


HEAD = ["model", "variant", "precision", "mean ms", "p50", "p90", "fps", "output"]


def _table(rows, head=HEAD):
    widths = [max(len(str(c)) for c in [h] + [r[i] for r in rows])
              for i, h in enumerate(head)]
    align = ["---" if i < 3 or i == 7 else "---:" for i in range(len(head))]
    out = ["| " + " | ".join(h.ljust(w) for h, w in zip(head, widths)) + " |",
           "| " + " | ".join(align) + " |"]
    for r in rows:
        out.append("| " + " | ".join(str(c).ljust(w)
                                     for c, w in zip(r, widths)) + " |")
    return "\n".join(out)


def render(runs):
    if not runs:
        return ("# Model comparison\n\n"
                "No benchmark results yet. Run a model's `onnx2trt.py`; it "
                "writes one JSON per configuration into `reports/bench/`.\n")

    lines = ["# Model comparison", ""]
    lines.append("Generated by `compare.py` from `reports/bench/*.json`. "
                 "Do not edit by hand -- rerun the script.")
    lines.append("")

    devices = sorted({r.get("device", "") for r in runs if r.get("device")})
    trts = sorted({(r.get("versions") or {}).get("tensorrt", "") for r in runs} - {""})
    stamps = sorted(r.get("timestamp", "") for r in runs if r.get("timestamp"))
    lines.append(f"- GPU: {', '.join(devices) or 'unrecorded'}")
    lines.append(f"- TensorRT: {', '.join(trts) or 'unrecorded'}")
    if stamps:
        lines.append(f"- Measured: {stamps[0][:10]} to {stamps[-1][:10]}")
    lines.append(f"- Runs: {len(runs)}")
    lines.append("")

    if len(devices) > 1:
        lines += ["> **Mixed hardware.** The rows below were not all measured "
                  "on the same GPU, so they are not comparable. Rerun on one "
                  "machine before reading anything into the ranking.", ""]

    # Group by profile, then input size. Latency across different input sizes
    # is not a like-for-like comparison.
    by_profile = defaultdict(lambda: defaultdict(list))
    for r in runs:
        by_profile[r.get("profile", "bench")][_size(r)].append(r)

    for profile in sorted(by_profile):
        lines.append(f"## Profile `{profile}`")
        lines.append("")
        sizes = by_profile[profile]
        for size in sorted(sizes, key=lambda s: -len(sizes[s])):
            group = sizes[size]
            lines.append(f"### Input {size}"
                         + ("" if len(group) > 1 else "  (single model)"))
            lines.append("")
            lines.append(_table(list(_rows(group))))
            lines.append("")
            # Per-run notes: which encoder, which checkpoint. Two runs of the
            # same model with different weights are different measurements and
            # the table has to say so.
            noted = [(r["model"], r["notes"]) for r in group if r.get("notes")]
            if noted:
                lines += [f"- `{m}` -- {n}" for m, n in sorted(set(noted))]
                lines.append("")

        if len(sizes) > 1:
            lines += [
                "Latency is **not** comparable across the sections above. "
                "Attention cost grows faster than pixel count -- measured on "
                "`depth_anything_ac`, 1.35x the pixels cost 1.70x the time -- "
                "so dividing by resolution does not rescue the comparison.",
                "",
            ]

    present = {r["model"] for r in runs}
    notes = [(m, c) for m, c in sorted(CAVEAT.items()) if m in present]
    if notes:
        lines += ["## Caveats", "",
                  "These numbers are valid as latency. The *output* carries a "
                  "condition recorded in `docs/model_contracts.md`.", ""]
        lines += [f"- `{m}` -- {c}" for m, c in notes]
        lines.append("")

    missing = sorted(set(KIND) - present)
    if missing:
        lines += ["## Not measured", "",
                  "No result file exists for these yet, so they are absent "
                  "from the tables above rather than slow:", "",
                  ", ".join(f"`{m}`" for m in missing), ""]

    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--bench-dir", default=BENCH_DIR)
    ap.add_argument("--out", default=OUT)
    ap.add_argument("--check", action="store_true",
                    help="do not write; exit 1 if the file is stale")
    args = ap.parse_args()

    text = render(load_all(args.bench_dir))

    if args.check:
        old = (open(args.out, encoding="utf-8").read()
               if os.path.exists(args.out) else "")
        if old != text:
            print(f"{args.out} is out of date - run: python compare.py")
            return 1
        print(f"{args.out} is up to date")
        return 0

    os.makedirs(os.path.dirname(args.out), exist_ok=True)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    print(f"wrote {args.out}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
