"""Generate the MoGe ONNX exporter A/B report from captured JSON evidence."""

import glob
import json
import os
import re
import statistics


ROOT = os.path.dirname(os.path.abspath(__file__))
RESULTS = os.path.join(ROOT, "reports", "tune", "moge_ab")
LABELS = {
    "dynamo_raw": "Dynamo / raw",
    "dynamo_sim": "Dynamo / simplified (current)",
    "legacy_raw": "TorchScript / raw",
    "legacy_sim": "TorchScript / simplified",
}
GRAPH_VARIANTS = {
    "moge-2_vits_normal_388x518_ab_dynamo.onnx": "dynamo_raw",
    "moge-2_vits_normal_388x518_ab_dynamo_sim.onnx": "dynamo_sim",
    "moge-2_vits_normal_388x518_ab_legacy.onnx": "legacy_raw",
    "moge-2_vits_normal_388x518_ab_legacy_sim.onnx": "legacy_sim",
}


def load_builds():
    grouped = {name: [] for name in LABELS}
    for path in glob.glob(os.path.join(RESULTS, "ab_*_r*.json")):
        match = re.fullmatch(r"ab_(.+)_r(\d+)\.json", os.path.basename(path))
        if not match or match.group(1) not in grouped:
            continue
        row = json.load(open(path, encoding="utf-8"))[0]
        grouped[match.group(1)].append((int(match.group(2)), row))
    for variant, rows in grouped.items():
        rows.sort()
        if len(rows) != 3:
            raise RuntimeError(f"{variant}: expected 3 completed builds, got {len(rows)}")
    return grouped


def pct(value):
    return f"{value * 100:.2f}%"


def main():
    builds = load_builds()
    graph_payload = json.load(open(os.path.join(RESULTS, "graphs.json"), encoding="utf-8"))
    accuracy = json.load(open(os.path.join(RESULTS, "accuracy.json"), encoding="utf-8"))
    equivalence = json.load(open(os.path.join(RESULTS, "onnx_equivalence.json"), encoding="utf-8"))

    graph_rows = {}
    baseline_graph = None
    for graph in graph_payload["graphs"]:
        variant = GRAPH_VARIANTS.get(graph["name"])
        if variant:
            graph_rows[variant] = graph
        else:
            baseline_graph = graph
    if baseline_graph is None or set(graph_rows) != set(LABELS):
        raise RuntimeError("graphs.json does not contain the baseline and all four variants")

    stats = {}
    for variant, rows in builds.items():
        records = [row for _, row in rows]
        times = [row["stats"]["mean_ms"] for row in records]
        reformat = statistics.mean(
            row["layer_type_time_shares"].get("Reformat", 0.0) for row in records)
        slice_share = statistics.mean(
            row["layer_type_time_shares"].get("Slice", 0.0) for row in records)
        fp32 = statistics.mean(
            row["profile_summary"]["fp32_output_share"] for row in records)
        stats[variant] = {
            "times": times,
            "mean": statistics.mean(times),
            "span": (max(times) - min(times)) / statistics.mean(times),
            "movement": reformat + slice_share,
            "fp32": fp32,
        }

    best = min(stats, key=lambda name: stats[name]["mean"])
    worst = max(stats, key=lambda name: stats[name]["mean"])
    mean_gap = stats[worst]["mean"] / stats[best]["mean"] - 1.0
    exact_reexport = graph_rows["dynamo_sim"]["sha256"] == baseline_graph["sha256"]

    accuracy_bad = [row for row in accuracy if row.get("verdict") != "ok"]
    accuracy_worst = max(row["worst_rel"] for row in accuracy)
    equivalent_outputs = [out for row in equivalence["results"] for out in row["outputs"]]
    equivalence_worst = max(out["relative_mean"] for out in equivalent_outputs)
    array_corrs = [out["correlation"] for out in equivalent_outputs
                   if out["correlation"] is not None]

    lines = [
        "# MoGe ONNX exporter A/B",
        "",
        "Generated by `summarize_moge_ab.py` from the JSON files in this directory.",
        "The published ONNX, engine, and `reports/bench` record were not replaced.",
        "",
        "## Conditions",
        "",
        "- Model/input: `moge_2`, 388x518, fp16, TensorRT default optimization level 3.",
        "- Hardware: RTX 3080 10 GB. GPU graphics clock was checked before and",
        "  repeatedly during the run; every observation was 1800 MHz.",
        "- Three independent builds per graph, with separate fingerprints and timing",
        "  caches. Variant order changed each round to distribute time/temperature drift.",
        "- Each engine: 20 warmup + 100 timed end-to-end inference iterations, then 10",
        "  profiler iterations. Profile percentages are shares, not benchmark latency.",
        "",
        "## Graphs",
        "",
        "| graph | nodes | Reshape | Transpose | Pad | Slice | Cast |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for variant in LABELS:
        graph = graph_rows[variant]
        ops = graph["operators"]
        lines.append(
            f"| {LABELS[variant]} | {graph['nodes']} | {ops['Reshape']} | "
            f"{ops['Transpose']} | {ops['Pad']} | {ops['Slice']} | {ops['Cast']} |")

    lines += [
        "",
        "The re-exported current graph is " +
        ("byte-identical" if exact_reexport else "not byte-identical") +
        f" to the published ONNX (`sha256 {baseline_graph['sha256']}`).",
        "",
        "## TensorRT results",
        "",
        "| graph | build 1 | build 2 | build 3 | mean | build span | Reformat+Slice | fp32 |",
        "| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |",
    ]
    for variant in LABELS:
        row = stats[variant]
        runs = " | ".join(f"{value:.3f}" for value in row["times"])
        lines.append(
            f"| {LABELS[variant]} | {runs} | **{row['mean']:.3f} ms** | "
            f"{pct(row['span'])} | {pct(row['movement'])} | {pct(row['fp32'])} |")

    lines += [
        "",
        "## Correctness",
        "",
        f"- ONNX against the published graph: worst mean relative difference "
        f"{equivalence_worst * 100:.6f}%; minimum reported array-output correlation "
        f"{min(array_corrs):.9f}.",
        f"- TensorRT against its own ONNX: {len(accuracy) - len(accuracy_bad)}/"
        f"{len(accuracy)} engines `ok`; worst mean relative output error "
        f"{pct(accuracy_worst)}.",
        "",
        "## Decision",
        "",
        f"Keep **{LABELS['dynamo_sim']}**. It had the lowest mean and smallest build "
        f"span in this run, but the largest mean difference among all four graphs was "
        f"only {pct(mean_gap)}, below this project's 2% decision threshold.",
        "",
        "Reducing ONNX Reshape/Slice nodes did not reduce the engine's data-movement",
        f"share: Reformat+Slice remained {pct(min(row['movement'] for row in stats.values()))}–"
        f"{pct(max(row['movement'] for row in stats.values()))}. The cost is therefore not",
        "removed by switching exporter or simplification. The remaining Pad/Reformat cost",
        "comes from the model's replicate-padding structure; changing it would change the model.",
        "",
        "Raw evidence: the twelve `ab_*_r*.json` files, `graphs.json`,",
        "`onnx_equivalence.json`, and `accuracy.json` beside this report.",
        "",
    ]
    out = os.path.join(RESULTS, "README.md")
    with open(out, "w", encoding="utf-8", newline="\n") as handle:
        handle.write("\n".join(lines))
    print(os.path.relpath(out, ROOT))


if __name__ == "__main__":
    main()
